name: 'Update dependencies'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
        
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
